c ****************************************************
c   FRANK MANU
c   SPRING 2020
c   EECE.5200 - COMPUTER AIDED ENGINEERING ANAYLSIS
c   PROBLEM SET 3 - PART 1
c ****************************************************

	PARAMETER (LDA=10, N=3)
	REAL A(LDA,LDA),B(LDA),C(LDA)
	REAL WR(LDA), WI(LDA), Z(LDA,LDA)

	COMPLEX COMPLEX_E(LDA,LDA)
	COMPLEX COMPLEX_C(LDA),COMPLEX_D(LDA)

c[] MATRIX B DEFINITION
	DATA (B(J),J=1,3)   / 0.0, 0.0, 20.0/

c[] MATRIX A DEFINITION
	DATA (A(1,J),J=1,3) / 0.0, 1.0, 0.0/
	DATA (A(2,J),J=1,3) / 0.0, 0.0, 1.0/
	DATA (A(3,J),J=1,3) / -6.0,-11.0,-6.0/

c[] MATRIX C DEFINITION
	DATA (C(J),J=1,3)   / 60.0, 16.0, 1.0/

C[] FIND THE EIGEN VALUES AND EIGEN VECTORS STATE MATRIX:
	CALL EIGEN(LDA,N,A,WR,WI,Z)

	PRINT *,'THE EIGENVALUES ARE:'

	WRITE(*,*) 1,WR(1),WI(1)
	WRITE(*,*) 2,WR(2),WI(2)
	WRITE(*,*) 3,WR(3),WI(3)

	PRINT *,'THE EIGEN VECTORS ARE:'
	WRITE (*,*) ((Z(J,K),K=1,N),J=1,N)

C[] FIND THE STATE TRANSITION MATRIX OF THE SYSTEM
	J=1
	DO WHILE(J.LE.N)
		IF(WI(J).NE.0.0) THEN
			DO I=1,N
				COMPLEX_E(I,J) = CMPLX(Z(I,J), Z(I,J+1))
				COMPLEX_E(I,J+1) = CMPLX(Z(I,J),-Z(I,J+1))
			ENDDO
			WRITE(*,*) 'CMPLX',J
			J=J+2

C[] REAL:
		ELSE
			DO I=1,N
				COMPLEX_E(I,J)  = CMPLX(Z(I,J),0.0)
			ENDDO
			J=J+1
		ENDIF
	ENDDO

C[] GIVEN THAT U(t) = DELTA(t) FIND THE FORCED RESPONSE OF THE SYSTEM
	DO J=1,N
		COMPLEX_C(J) =CMPLX(0.0,0.0)
		DO I=1,N
			COMPLEX_C(J) = COMPLEX_C(J) +C(I)*COMPLEX_E(I,J)
		ENDDO
	ENDDO

	DO I=1,N
		B(I  ) = B(I)
		B(I+N) = 0.0
		DO J=1,N
			A(I  ,J  ) =  REAL (COMPLEX_E(I,J))
			A(I  ,J+N) = -AIMAG(COMPLEX_E(I,J))
			A(I+N,J  ) =  AIMAG(COMPLEX_E(I,J))
			A(I+N,J+N) =  REAL (COMPLEX_E(I,J))
		ENDDO
	ENDDO

	CALL GESS (2*N,A,LDA,B,LDA,1,COND)

	DO I=1,N
		COMPLEX_D(I) = CMPLX( B(I),B(I+N))
	ENDDO

C[] PRINT THE PULSE RESPONSE FUNCTIONS
	DO I=1,N
		COMPLEX_D(I) = COMPLEX_D(I)*COMPLEX_C(I)
	ENDDO

	PRINT *,'THE PULSE RESPONSE:'
	DO I=1,N
		WRITE(*,*) 'Y(t) = +', COMPLEX_D(I), '*10^[ ', CMPLX(WR(I),WI(I)), 't]'
	ENDDO

	END
